'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';

export default function Home(){
 const [mode,setMode]=useState('login');
 const [name,setName]=useState('');
 const [email,setEmail]=useState('');
 const [password,setPassword]=useState('');
 const [message,setMessage]=useState('');
 const [loading,setLoading]=useState(false);
 const [user,setUser]=useState(null);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user||null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>subscription.unsubscribe()},[]);
 async function submit(e){e.preventDefault();setLoading(true);setMessage('');try{if(mode==='register'){const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)throw error;setMessage('Hesabın oluşturuldu. E-posta doğrulaması açıksa gelen kutunu kontrol et.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setMessage('Giriş başarılı.')}}catch(err){setMessage(err.message||'Bir hata oluştu.')}finally{setLoading(false)}}
 async function resetPassword(){if(!email){setMessage('Önce e-posta adresini yaz.');return}const {error}=await supabase.auth.resetPasswordForEmail(email);setMessage(error?error.message:'Şifre sıfırlama bağlantısı e-posta adresine gönderildi.')}
 async function logout(){await supabase.auth.signOut();setMessage('Çıkış yapıldı.')}
 if(user)return <main className="shell"><section className="brand"><div className="logo">DH</div><h1>Deneme Harmanı</h1><p>Hoş geldin.</p></section><section className="card"><h2>Hesabın hazır</h2><p className="muted">{user.email}</p><p>Giriş sistemi çalışıyor. Sıradaki adım ana çalışma ekranını hazırlamak.</p><button className="primary" onClick={logout}>Çıkış Yap</button></section></main>;
 return <main className="shell"><section className="brand"><div className="logo">DH</div><h1>Deneme Harmanı</h1><p>Kendi kaynaklarından, kendi denemeni oluştur.</p><div className="features"><span>PDF’lerini düzenle</span><span>Karma denemeler oluştur</span><span>Gelişimini takip et</span></div></section><section className="card"><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setMessage('')}}>Giriş Yap</button><button className={mode==='register'?'active':''} onClick={()=>{setMode('register');setMessage('')}}>Kayıt Ol</button></div><h2>{mode==='login'?'Tekrar hoş geldin':'Aramıza katıl'}</h2><p className="muted">{mode==='login'?'Çalışmalarına kaldığın yerden devam et.':'Kişisel çalışma alanını birkaç saniyede oluştur.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Ad Soyad<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Adın ve soyadın" autoComplete="name"/></label>}<label>E-posta<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ornek@email.com" autoComplete="email"/></label><label>Şifre<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="6" placeholder="En az 6 karakter" autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode==='login'&&<div className="row"><span></span><button className="link" type="button" onClick={resetPassword}>Şifremi unuttum</button></div>}<button className="primary" disabled={loading} type="submit">{loading?'Lütfen bekle...':mode==='login'?'Giriş Yap':'Hesap Oluştur'}</button></form>{message&&<p className="muted">{message}</p>}<div className="secure">🔒 Bilgilerin güvenli şekilde korunur.</div></section></main>
}